name: Refresh

on:
  schedule:
    # don't really care when it runs, just want it to run once a day
    # running it at the top of the hour is more likely to get dropped
    # or delayed due to high load, so arbitrarily run it at 11:37 AM UTC
    - cron: "37 11 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Script for Prod
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"refresh": "authorized"}' https://net-worth-tracker-3c5c.fly.dev/api/accounts/refresh
      - name: Run Script for Staging
        run: |
          curl -X POST -H 'Content-Type: application/json' -d '{"refresh": "authorized"}' https://net-worth-tracker-3c5c-staging.fly.dev/accounts/refresh
